dotenv: .env

etherscan:
  api_key: ${ETHERSCAN_TOKEN}

dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.8.2

compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.8.2'
